openapi: 3.0.3
info:
  title: Supabase → Z-API (Docs)
  version: "1.0.0"
  description: |
    Documentação ilustrativa do fluxo:
    - Lê contatos ativos no Supabase
    - Envia mensagem personalizada via Z-API

servers:
  - url: http://localhost
    description: "Somente ilustrativo (não há servidor HTTP neste projeto)"

paths:
  /contacts:
    get:
      summary: "Listar contatos ativos (Supabase)"
      description: >
        Este endpoint é apenas documentação do que o script faz ao consultar o Supabase.
        Não existe rota HTTP no projeto; isto é uma representação.
      parameters:
        - in: query
          name: limit
          required: false
          schema:
            type: integer
            minimum: 1
            default: 3
          description: "Número máximo de contatos"
      responses:
        "200":
          description: "Contatos retornados"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ContactsResponse"
              examples:
                demo:
                  value:
                    count: 3
                    items:
                      - id: "1206b580-aaaa-bbbb-cccc-111111111111"
                        name: "Breno"
                        phone: "5518996628576"
                        active: true
                      - id: "a389c618-aaaa-bbbb-cccc-222222222222"
                        name: "Washington"
                        phone: "5511948054059"
                        active: true
                      - id: "dba0426c-aaaa-bbbb-cccc-333333333333"
                        name: "Carla"
                        phone: "5581999999999"
                        active: true

  /send-message:
    post:
      summary: "Enviar mensagem via Z-API"
      description: >
        Documenta a chamada que o script faz para a Z-API usando o header `Client-Token`.
        Representação apenas para fins de documentação.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SendMessageRequest"
            examples:
              demo:
                value:
                  phone: "5511999999999"
                  message: "Ola Breno, tudo bem com voce?"
      responses:
        "200":
          description: "Resposta encaminhada da Z-API"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SendMessageResponse"
        "400":
          description: "Payload invalido ou token ausente"

components:
  schemas:
    Contact:
      type: object
      required: [id, name, phone, active]
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        phone:
          type: string
          description: "Numero E.164 apenas digitos (ex.: 5511999999999)"
        active:
          type: boolean

    ContactsResponse:
      type: object
      properties:
        count:
          type: integer
        items:
          type: array
          items:
            $ref: "#/components/schemas/Contact"

    SendMessageRequest:
      type: object
      required: [phone, message]
      properties:
        phone:
          type: string
          example: "5511999999999"
        message:
          type: string
          example: "Ola Breno, tudo bem com voce?"

    SendMessageResponse:
      type: object
      properties:
        ok:
          type: boolean
          example: true
        status:
          type: integer
          example: 200
        data:
          type: object
          nullable: true
          example:
            messageId: "abcd-1234"
